apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-config
data:
  frontend.env: |
    REACT_APP_API_URL=http://resume-backend-service:5000
    REACT_APP_ENVIRONMENT=production
    REACT_APP_APP_NAME=Resume AI Interview
  backend.env: |
    NODE_ENV=production
    PORT=5000
    CORS_ORIGIN=http://resume-frontend-service
    LOG_LEVEL=info
