apiVersion: v1
kind: Secret
metadata:
  name: resume-secrets
type: Opaque
data:
  # Base64 encoded values
  mongodb-username: YWRtaW4= # admin
  mongodb-password: cGFzc3dvcmQxMjM= # password123
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQHJlc3VtZS1tb25nb2RiLXNlcnZpY2U6MjcwMTcvcmVzdW1lX3Byb2R1Y3Rpb24=
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleQ== # your_jwt_secret_key
